name: Test
on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: hashicorp/setup-terraform@v1
        with:
          # TODO: 1.3.0 has the experimental optional values as a feature and throws errors: need to migrate to final feature.
          terraform_version: 1.2.9

      - name: Test
        run: tests/run.sh

